spring:
  data:
    rest:
      base-path: /api

management:
  context-path: /admin
  security:
   role: ADMIN

shell:
  simple:
    user:
      name: admin
      password: admin

endpoints:
  sensitive: true

logging:
  level:
    root: INFO
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG
#    org.springframework.boot.autoconfigure.security: DEBUG
#    org.springframework.security: DEBUG